import test from 'node:test';
import assert from 'node:assert/strict';
import {productionExecutionSafe} from './production-evidence';
import {deriveResolution,resolutionContract,type ResolutionSnapshot,type ResolutionChoices} from './workflow-resolution';
import {resolveWorkflow,shouldAppearInApproved} from './resolved-workflow';
import {continuationChildId,continuationIntentId} from './workflow-continuation-token';
const id='00000000-0000-4000-8000-000000000001',actor='00000000-0000-4000-8000-000000000002';
const stamp='2026-10-01T12:00:00Z';
function deriveProductionResolution(s:ResolutionSnapshot, choices:ResolutionChoices={}) {
 return deriveResolution({...s,executionSafe:s.executionSafe && productionExecutionSafe(id,[...(s.evidence.parent?[s.evidence.parent]:[]),...s.evidence.uploads,...s.evidence.icons,...s.evidence.mediref],s.events)},choices);
}
function fixture():ResolutionSnapshot {
 const parent=continuationIntentId(id);
 return {draft:{id,status:'approved',provider_approved_at:stamp,edited_text:'Synthetic approved letter',praktika_patient_id:'123',workflow_status:'failed',workflow_praktika_upload_status:'failed',workflow_icon_update_status:'pending',workflow_mediref_status:'failed',workflow_periodontal_chart_status:'not_requested'},
  evidence:{parent:{id:parent,app_user_id:actor,job_type:'complete_report_workflow',status:'failed',request:{reportDraftId:id,actorUserId:actor,options:{actor:{actorUserId:actor},attachPeriodontalChart:false,praktikaPatientId:'123'}},response:{stage:'upload',medirefPreparationFailure:{contract:'mediref-no-job-failure-v1',insertionOutcome:'not_attempted',externalExecution:'not_started',deadlineExceeded:false,stage:'pdf_generation',code:'MEDIREF_PDF_GENERATION_FAILED'}},created_at:stamp},uploads:[],icons:[],mediref:[],currentUploadId:continuationChildId(parent,'upload_report_to_praktika'),currentIconId:continuationChildId(parent,'update_praktika_letter_icons'),livePraktikaActors:new Set(),liveMediref:false},
  fingerprint:'a'.repeat(64),letterFingerprint:'b'.repeat(64),events:[],executionSafe:true};
}
function upload(s:ResolutionSnapshot){s.evidence.uploads=[{id:s.evidence.currentUploadId!,status:'completed',job_type:'upload_report_to_praktika',app_user_id:actor,request:{reportDraftId:id,continuationId:s.evidence.parent!.id},response:{patient_communication:{iFileId:42}},created_at:stamp,completed_at:stamp}];}
function icon(s:ResolutionSnapshot){s.evidence.icons=[{id:s.evidence.currentIconId!,status:'completed',job_type:'update_praktika_letter_icons',request:{reportDraftId:id,continuationId:s.evidence.parent!.id,method:'POST',path:'/php/forms/db_commitFormData.php',contentType:'json',body:[{practice_id:1181,appointment_id:456,appointment_icon1id:6597,appointment_icon2id:0,appointment_icon3id:0,appointment_icon4id:0}]},response:{appointment_icon1id:6597,appointment_icon2id:0,appointment_icon3id:0,appointment_icon4id:0},created_at:stamp,completed_at:stamp}];}
const absent:ResolutionChoices={praktika:'incomplete',icon:'incomplete',mediref:'incomplete'};
test('Sidaway: missing-helper verified absence derives only upload, icon, MediRef work',()=>{
 const s=fixture(),before=JSON.stringify(s);const d=deriveProductionResolution(s,absent);assert.equal(d.action,'resume');assert.deepEqual(d.plan,['praktika','icon','mediref']);assert.equal(d.rows.find(r=>r.branch==='periodontal')?.state,'skipped');assert.equal(JSON.stringify(s),before);assert.equal(s.evidence.uploads.length,0);assert.equal(Object.hasOwn(s.evidence.parent?.response as object,'manualVerification'),false);
});
test('missing-helper absence alone does not authorize replay',()=>assert.equal(deriveProductionResolution(fixture()).action,null));
test('execution uncertainty blocks every classification and action',()=>{const s=fixture();s.executionSafe=false;for(const choices of [absent,{praktika:'completed',icon:'completed',mediref:'completed'}] as ResolutionChoices[]){const d=deriveProductionResolution(s,choices);assert.equal(d.eligible,false);assert.equal(d.action,null);assert.equal(d.rows.some(r=>r.verifiable),false);}});
test('Kaur: valid preparation sent:false is retained and not duplicated',()=>{
 const s=fixture();s.evidence.mediref=[{id:'med',job_type:'send_mediref_letter',status:'completed',payload:{draftId:id,workflowContinuationId:s.evidence.parent!.id},result:{prepared:true,sent:false,remoteDraftSaved:true},created_at:stamp}];
 const d=deriveProductionResolution(s,{praktika:'incomplete',icon:'incomplete'});assert.equal(d.action,'resume');assert.deepEqual(d.plan,['praktika','icon']);const row=d.rows.find(r=>r.branch==='mediref')!;assert.equal(row.state,'automated_completed');assert.equal(row.delivery,'not_sent');assert.equal(row.verifiable,false);assert.equal(deriveProductionResolution(s,absent).eligible,false);
});
test('Phaedra: confirmed upload is omitted; remaining work can be manually completed',()=>{const s=fixture();upload(s);s.draft.workflow_periodontal_chart_status='pending';(s.evidence.parent!.request!.options as Record<string,unknown>).attachPeriodontalChart=true;const d=deriveProductionResolution(s,{icon:'completed',mediref:'completed',periodontal:'completed'});assert.equal(d.action,'complete');assert.deepEqual(d.plan,[]);assert.equal(d.rows.find(r=>r.branch==='praktika')?.verifiable,false);});
test('Debbie: confirmed upload/icons are omitted; no repeated work',()=>{const s=fixture();upload(s);icon(s);s.draft.workflow_periodontal_chart_status='pending';const d=deriveProductionResolution(s,{mediref:'completed',periodontal:'completed'});assert.equal(d.action,'complete');assert.deepEqual(d.plan,[]);assert.deepEqual(d.rows.filter(r=>r.verifiable).map(r=>r.branch),['mediref','periodontal']);});
test('unsupported artifact dependencies offer Save verification',()=>{const s=fixture();s.draft.workflow_periodontal_chart_status='pending';assert.equal(deriveProductionResolution(s,{...absent,periodontal:'incomplete'}).action,'save');});
test('parentless missing execution evidence blocks classification and replay',()=>{const s=fixture();delete s.evidence.parent;s.executionSafe=false;for(const choices of [absent,{praktika:'completed',icon:'completed',mediref:'completed'}] as ResolutionChoices[]){assert.equal(deriveProductionResolution(s,choices).action,null);assert.equal(deriveProductionResolution(s,choices).eligible,false);}assert.equal(s.evidence.parent,undefined);});
test('existing completed branch cannot be reclassified as incomplete',()=>{const s=fixture();upload(s);assert.equal(deriveProductionResolution(s,absent).eligible,false);});
test('manual evidence remains distinct from automated proof and closure removes card',()=>{
 const s=fixture();const event={id:'event',action:'workflow_resolution_verification',entity_id:id,details:{contract:resolutionContract,version:1,draftId:id,letterFingerprint:s.letterFingerprint,branch:'praktika',outcome:'completed',actorUserId:actor,verifiedAt:stamp}};
 s.evidence.resolution={draftId:id,letterFingerprint:s.letterFingerprint,executionSafe:true,events:[event]};let r=resolveWorkflow(s.draft,s.evidence);assert.equal(r.branches.praktika,'completed');assert.equal(r.branchEvidence?.praktika?.automated,'unknown');assert.equal(r.branchEvidence?.praktika?.manual,'completed');assert.equal(r.status,'needs_attention');
 s.evidence.resolution.events.push({id:'closure',action:'workflow_resolution_completed',details:{contract:resolutionContract,version:1,draftId:id,letterFingerprint:s.letterFingerprint,actorUserId:actor,completedAt:stamp}});r=resolveWorkflow(s.draft,s.evidence);assert.equal(r.status,'completed');assert.equal(r.completedAt,null);assert.equal(shouldAppearInApproved({...s.draft,workflow_resolved:r}),false);
});
test('uncertain execution overrides human closure',()=>{const s=fixture();s.evidence.resolution={draftId:id,letterFingerprint:s.letterFingerprint,executionSafe:false,events:[{id:'closure',action:'workflow_resolution_completed',details:{contract:resolutionContract,version:1,draftId:id,letterFingerprint:s.letterFingerprint}}]};assert.equal(resolveWorkflow(s.draft,s.evidence).status,'needs_attention');});
test('invalid letter evidence cannot complete workflow',()=>{const s=fixture();s.evidence.resolution={draftId:id,letterFingerprint:s.letterFingerprint,executionSafe:true,events:[{id:'closure',action:'workflow_resolution_completed',details:{contract:resolutionContract,version:1,draftId:id,letterFingerprint:'wrong'}}]};assert.equal(resolveWorkflow(s.draft,s.evidence).status,'needs_attention');});
test('verified-incomplete evidence does not fabricate a failed helper',()=>{const s=fixture();s.evidence.resolution={draftId:id,letterFingerprint:s.letterFingerprint,executionSafe:true,events:[{id:'negative',action:'workflow_resolution_verification',details:{contract:resolutionContract,version:1,draftId:id,letterFingerprint:s.letterFingerprint,branch:'praktika',outcome:'incomplete',actorUserId:actor,verifiedAt:stamp}}]};const r=resolveWorkflow(s.draft,s.evidence);assert.equal(r.branches.praktika,'unknown');assert.equal(r.branchEvidence?.praktika?.manual,'incomplete');assert.equal(s.evidence.uploads.length,0);});

test('saved human completion remains human provenance in the next preview',()=>{
 const s=fixture();s.events=[{id:'human',entity_id:id,action:'workflow_resolution_verification',details:{contract:resolutionContract,version:1,draftId:id,letterFingerprint:s.letterFingerprint,branch:'praktika',outcome:'completed',actorUserId:actor,verifiedAt:stamp}}];
 const d=deriveProductionResolution(s,{icon:'incomplete',mediref:'incomplete'});const row=d.rows.find(r=>r.branch==='praktika')!;assert.equal(row.state,'manually_verified_completed');assert.equal(row.automated,'unknown');assert.equal(row.verifiable,false);assert.deepEqual(d.plan,['icon','mediref']);
});
